<?php

/**
 * @file
 * Implements core hooks for wetlit_layouts.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function wetkit_layouts_ctools_plugin_directory($module, $plugin) {
  if ($module == 'panels' && $plugin == 'layouts') {
    return 'plugins/layouts';
  }
}

/**
 * Implements hook_init().
 */
function wetkit_layouts_init() {
  global $theme;
  if ($theme == 'wetkit_rubik') {
    $url = parse_url(request_uri());
    if (strstr($url['path'], "/admin/structure/pages")) {
      drupal_add_css(drupal_get_path('module', 'wetkit_layouts') . '/css/layouts.css', array('group' => CSS_THEME, 'every_page' => TRUE));
    }
    if (strstr($url['path'], "/admin/dashboard")) {
      drupal_add_css(drupal_get_path('module', 'wetkit_layouts') . '/css/layouts.css', array('group' => CSS_THEME, 'every_page' => TRUE));
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function wetkit_layouts_form_alter(&$form, &$form_state, $form_id) {
  // Modify the Panels Change Layout Screen.
  if ($form_id == 'panels_change_layout') {
    $form['submit']['#submit'][] = '_wetkit_layouts_refresh_page';
    $form['display']['#prefix'] = '<div class="span-8">' . t('<strong>Important:</strong> You will need to manually refresh the page after you change the layout for it to take affect.') . '</div><div class="clear"></div>';
  }
}

/**
 * Implements _wetkit_layouts_refresh_page().
 *
 * TODO: Implement logic to force an auto refresh
 */
function _wetkit_layouts_refresh_page($form, $form_state) {

}

/**
 * Remove default sidebar related body classes and provide own css classes.
 */
function wetkit_layouts_preprocess_html(&$variables) {
  // Detect Panels Layout.
  $panel_page = page_manager_get_current_page();
  if ($panel_page) {
    // Panels Layout.
    $bodyid = '';
    if (isset($panel_page['handler']->conf['display']->renderer_handler->plugins['layout']['bodyid'])) {
      $bodyid = $panel_page['handler']->conf['display']->renderer_handler->plugins['layout']['bodyid'];
    }
    // Panelizer Layout.
    elseif (isset($panel_page['handler']->conf['context'])) {
      $context = $panel_page['handler']->conf['context'];
      if (isset($panel_page['contexts'][$context]->data->panelizer['page_manager']->display->renderer_handler->plugins['layout']['bodyid'])) {
        $bodyid = $panel_page['contexts'][$context]->data->panelizer['page_manager']->display->renderer_handler->plugins['layout']['bodyid'];
      }
    }
    // Set Body ID for Panels Layouts.
    $variables['wetkit_col_array'] = 'wb-body';
    if (!empty($bodyid)) {
      $variables['wetkit_col_array'] = $bodyid;
    }
  }
  // Detect Blocks Layout (Deprecated).
  else {
    if ($variables['is_front']) {
      $variables['wetkit_col_array'] = 'wb-body';
    }
    elseif (!empty($variables['page']['sidebar_first']) && !empty($variables['page']['sidebar_second'])) {
      $variables['wetkit_col_array'] = 'wb-body-sec';
    }
    elseif (!empty($variables['page']['sidebar_first'])) {
      $variables['wetkit_col_array'] = 'wb-body-sec';
    }
    elseif (!empty($variables['page']['sidebar_second'])) {
      $variables['wetkit_col_array'] = 'wb-body-sec';
    }
    else {
      $variables['wetkit_col_array'] = 'wb-body';
    }
  }
}
