<?php
/**
 * @file
 * wetkit_breadcrumbs.module
 */

include_once 'wetkit_breadcrumbs.features.inc';
include_once 'theme/wetkit_breadcrumbs.theme.inc';

/**
 * Implements hook_menu_breadcrumb_alter().
 */
function wetkit_breadcrumbs_menu_breadcrumb_alter(&$active_trail, $item) {
  foreach ($active_trail as $key => $bcrumb) {
    if ($bcrumb['href'] == '<group>' || $bcrumb['href'] == '<separator>') {
      unset($active_trail[$key]);
    }
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function wetkit_breadcrumbs_theme_registry_alter(&$theme_registry) {
  global $theme;
  global $base_theme_info;
  $internal_render = variable_get('path_breadcrumbs_internal_render', 1);
  $wetkit_base_theme = FALSE;

  foreach ($base_theme_info as $base) {
    if (!empty($base->name)) {
      if ($base->name == 'wetkit_adaptivetheme') {
        $wetkit_base_theme = TRUE;
      }
    }
  }

  if ($internal_render && (($theme == 'wetkit_adaptivetheme') || ($wetkit_base_theme == TRUE))) {
    $theme_registry['breadcrumb']['theme path'] = drupal_get_path('module', 'wetkit_breadcrumbs');
    $theme_registry['breadcrumb']['file'] = drupal_get_path('module', 'wetkit_breadcrumbs') . '/theme/wetkit_breadcrumbs.theme.inc';
    $theme_registry['breadcrumb']['function'] = 'wetkit_breadcrumbs_breadcrumb';
  }
}

/**
 * Implements hook_apps_app_info().
 */
function wetkit_breadcrumbs_apps_app_info() {
  return array(
    'configure form' => 'wetkit_breadcrumbs_configure_form',
  );
}

/**
 * Configuration Form for WetKit Breadcrumbs.
 *
 * @param array $form
 *   Nested array of form elements that comprise the form.
 * @param array $form_state
 *   A keyed array containing the current state of the form.
 */
function wetkit_breadcrumbs_configure_form($form, &$form_state) {
  drupal_add_js(drupal_get_path('module', 'system') . '/system.js');
  $form = array();
  $form['wetkit_breadcrumbs'] = array(
    '#title' => 'Breadcrumb Settings',
    '#type'  => 'fieldset',
    '#collapsible' => 'true',
  );
  $form['wetkit_breadcrumbs']['path_breadcrumbs_home_link_enabled'] = array(
    '#type' => 'checkbox',
    '#title' => t('Prepend breadcrumbs with a home link by default'),
    '#default_value' => variable_get('path_breadcrumbs_home_link_enabled', 1),
    '#description' => t('This value does not changes current breadcrumbs navigation. It is just set default value for new path breadcrumbs.'),
  );
  $form['wetkit_breadcrumbs']['path_breadcrumbs_home_link_title'] = array(
    '#type' => 'textfield',
    '#title' => t('Home link title'),
    '#default_value' => variable_get('path_breadcrumbs_home_link_title', 'Home'),
    '#description' => t('Title of the link that points to the front page.'),
    '#size' => 30,
  );
  $form['#submit'][] = 'wetkit_breadcrumbs_configure_form_submit';

  return system_settings_form($form);
}

/**
 * Handle submission of the WetKit Web Usability configuration page.
 *
 * @param array $form
 *   Nested array of form elements that comprise the form.
 * @param array $form_state
 *   A keyed array containing the current state of the form.
 */
function wetkit_breadcrumbs_configure_form_submit($form, &$form_state) {
  $values = $form_state['values'];

  // Truncate all cached data.
  cache_clear_all('*', PATH_BREADCRUMBS_CACHE_STORAGE, TRUE);
}
