<?php
/**
 * @file
 * Git integration for the wetkit_git module.
 */

/**
 * Implements hook_menu().
 */
function wetkit_git_menu() {
  $items['git_update'] =  array(
    'page callback' => '_git_update',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements _git_update().
 */
function _git_update() {
  exec('cd profiles/wetkit; git pull');
  exec('cd profiles/wetkit; git rev-parse HEAD', $x);

  $info = substr($x[0], 0, 7);
  drupal_set_message('Git updated to ' . $info);
  drupal_goto('admin/reports/status');
}

/**
 * Implements hook_requirements().
 */
function wetkit_git_requirements($phase) {
  $requirements = array();
  $t = get_t();

  exec('cd profiles/wetkit; git rev-parse HEAD', $x);
  if (is_array($x)) {
    $info = substr($x[0], 0, 7);
  }

  switch ($phase) {
    case 'runtime':
      $requirements['wetkit_git'] = array(
        'title' => $t('Git Revision'),
        'value' => $info . ' to update the current revision of Git from upstream: ' . l(t("Click Here"), 'git_update'),
        'severity' => REQUIREMENT_OK,
      );
      break;
  }
  return $requirements;
}
