<?php
/**
 * @file
 * Git integration for the wetkit_git module.
 */

/**
 * Implements hook_menu().
 */
function wetkit_git_menu() {
  $items['git_update'] = array(
    'page callback' => '_wetkit_git_update',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements _wetkit_git_update().
 */
function _wetkit_git_update() {
  exec('cd profiles/wetkit; git pull');

  // Get the current revision.
  exec('cd profiles/wetkit; git rev-parse HEAD', $x);
  if (is_array($x)) {
    $info_sha = drupal_substr($x[0], 0, 7);
  }
  // Get information about the remote origin.
  exec('cd profiles/wetkit; git remote show origin | grep Fetch', $y);
  if (is_array($y)) {
    $info_url = $y[0];
  }

  if (isset($info_sha) && isset($info_url)) {
    drupal_set_message(t('Git updated to: @info_sha from: @info_url', array(
      '@info_sha' => $info_sha,
      '@info_url' => $info_url,
    )));
    drupal_goto('admin/reports/status');
  }
}
