tinyMCE.addI18n('en.wetkitcleanup',{
title:"WET-BOEW Tools and Cleanup Operations",
description:"WET-BOEW Cleanup Operations allow quick access to common HTML cleanup and transformation operations",
convert_titles:"Convert titles",
demote_titles:"Demote all titles one level",
promote_titles:"Promote all titles one level",
hide_heading_from_index:"Hide heading from page index",
show_heading_in_index:"Show heading in page index",
convert_tables:"Convert tables",
convert_table_text:"Convert table to text",
convert_tables_text:"Convert All Tables to Text",
table_headers:"Table Headers",
first_row_headers:"First row column headers",
thead_col_headers:"THEAD sections column headers",
first_col_row_headers_active_table:"First column row headers (active table only)",
first_col_row_headers:"First column row headers",
add_header_ids:"Add ID's and Headers to table",
change_selection_case:"Change Selection Case",
uppercase:"Uppercase",
lowercase:"Lowercase",
sentence_case:"Sentence Case",
title_case:"Title Case",
other_cleanup:"Other Cleanup",
quick_fix_all:"Quick Fix All",
remove_empty_blocks:"Remove empty h# and p blocks",
remove_table_dimensions:"Remove table width/height settings",
remove_table_dimensions_active:"Remove table width/height settings (active table only)",
convert_cell_alignments:"Convert cell alignments to styles",
right_align_data:"Right-align numeric data cells",
join_number_groups:"Join Groups of Numbers",
set_language:"Set Selection Language",
set_language_en:"English",
set_language_fr:"French",
extract_column:"Extract Column Content",
split_content_ef:"Split Columns as English|French",
split_content_fe:"Split Columns as French|English",
extract_column_1:"First Column of Tables",
extract_column_2:"Second Column of Tables",
not_exists_chosen_column:"The chosen column doesn't exist",
process_acronyms:"Process Acronyms",
process_acronyms_saved:"Process saved list of terms",
process_acronyms_custom:"Prompt for term and replacement",
term:"Term to find",
expanded:"Expanded Text",
abbr:"Use ABBR tag?",
abbr_yes:"Yes",
abbr_no:"No",
expand_all:"Expand All",
no_heading_selected:"No heading selected. Please ensure that your cursor is in a heading to use this action.",
tool_title:"Please select text in the same block",
no_table_selected:"No table selected. Please ensure that you are within a table to use this action."
});
