tinyMCE.addI18n('fr.wetkitcleanup',{
title:"WET-BOEW Outils et Opérations de nettoyages",
description:"WET-BOEW Outils et Opérations de nettoyages permet accès facile à des opérations de transformation du HTML",
convert_titles:"Convertir les titres",
demote_titles:"Convertir tous les titres au niveau inférieur",
promote_titles:"Convertir tous les titres au niveau supérieur",
hide_heading_from_index:"Masquer l`en tête dans l`index des pages",
show_heading_in_index:"Afficher l`en tête dans l`index des pages",
convert_tables:"Convertir les tableaux",
convert_table_text:"Convertir tableau à du texte",
convert_tables_text:"Convertir tous les tableaux à du texte",
table_headers:"En-têtes du tableau",
first_row_headers:"En-têtes de colonne de la première rangée",
thead_col_headers:"En-têtes de colonne des sections THEAD",
first_col_row_headers_active_table:"En-têtes de rangée de la première colonne (tableau actif seulement)",
first_col_row_headers:"En-têtes de rangée de la première colonne",
add_header_ids:"Ajouter ID et en-têtes au tableau",
change_selection_case:"Changer la casse de la sélection",
uppercase:"Majuscules",
lowercase:"Miniscules",
sentence_case:"Casse de la Phrase",
title_case:"Casse du titre",
other_cleanup:"Autres outils de nettoyage",
quick_fix_all:"Rapidement corriger tout",
remove_empty_blocks:"Retirer les h# et p blocs qui sont vides",
remove_table_dimensions:"Retirer les réglages du largeur/hauteur du tableau",
remove_table_dimensions_active:"Retirer les réglages du largeur/hauteur du tableau (tableau actif seulement)",
convert_cell_alignments:"Convertir alignements de cellules à des styles",
right_align_data:"Aligner à droite cellules de données numériques",
join_number_groups:"Joigner les groupes de numéros",
set_language:"Définir la langue de la section",
set_language_en:"anglais",
set_language_fr:"français",
extract_column:"Extraire colonne contenu",
split_content_ef:"Fendre les colonnes Anglais|Français",
split_content_fe:"Fendre les colonnes Français|Anglais",
extract_column_1:"Premier colonne du tableau",
extract_column_2:"Deuxième colonne du tableau",
not_exists_chosen_column:"Le colonne choisit n'existe pas",
process_acronyms:"Traiter les acronyms",
process_acronyms_saved:"Traiter liste des termes sauvegardé",
process_acronyms_custom:"Invite à entrer le terme et son remplacement",
term:"Terme pour trouver",
expanded:"Texte élargi",
abbr:"Utiliser marqueur ABBR?",
abbr_yes:"Oui",
abbr_no:"Non",
expand_all:"Tout Montrer",
no_heading_selected:"Aucune en-tête de section sélectionnée. Assurez vous que votre curseur se trouve dans une en-tête de section pour utiliser cette action.",
tool_title:"Veuillez sélectionner du texte dans le même bloc",
no_table_selected:"Aucun tableau sélectionné. Assurez-vous que vous que votre curseur se trouve dans un tableau pour utiliser cette action."
});
