<?php
/**
 * @file
 * Code for the wetkit_language feature.
 */

include_once('wetkit_language.features.inc');

/**
 * Implements hook_form_alter().
 *
 * @param type $form
 *   Nested array of form elements that comprise the form.
 * @param type $form_state
 *   A keyed array containing the current state of the form.
 * @param type $form_id 
 *   String representing the name of the form itself.
 */
function wetkit_language_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'wetkit_page_node_form' || $form_id == 'wetkit_page_other_node_form') {
    unset($form['translation']);
  }
}

/**
 * Implements hook_preprocess_page().
 *
 * @param array $vars
 *   The variables array that can be modified in place.
 */
function wetkit_language_preprocess_page(&$vars) {
  //Language Switcher Code
  $vars['menu_lang_bar'] = _language_switcher_wetkit();
}

/**
 * Implements hook_preprocess_panes_pane().
 *
 * @param array $vars
 *   The variables array that can be modified in place.
 */
function wetkit_language_preprocess_panels_pane(&$vars) {
  if ($vars['pane']->type == 'node_links') {
    if (isset($vars['content']['translation'])) {
      unset($vars['content']['translation']);
    }
  }
}

/**
 * Implements hook_preprocess_page().
 */
function wetkit_language_preprocess_maintenance_page(&$vars) {
  //Language Switcher Code
  $vars['menu_lang_bar'] = _language_switcher_wetkit();
}

/**
 * Implements hook_init().
 */
function wetkit_language_init() {
  //Set Flag
  if (variable_get('wetkit_language_revert', 1) == 1) {
    //wetkit_language_features_revert(array('wetkit_language'));
    variable_set('wetkit_language_revert', 0);
  }
}

/**
 * Implements hook_language_init().
 */
function wetkit_language_language_init() {
  //Set Flag
  if (variable_get('wetkit_language_db', 1) == 1) {
  }
}

/**
 * Implements _language_switcher_wetkit().
 *
 * @global type $language
 *   The global language identifier
 * @return type
 *   Returns the language switcher
 */
function _language_switcher_wetkit() {
  global $language;
  $term = '';
  $language_paths = '';
  $language_terms = '';

  $languages = language_list('enabled');
  $path = drupal_is_front_page() ? '<front>' : $_GET['q'];

  // handle node translations
  if (arg(0) == 'node' && arg(1)>0) {
    $node_path = 'node/' . arg(1);
    $language_paths = translation_path_get_translations($node_path);
  }

  // handle term translations
  if (arg(0) == 'taxonomy' && arg(1) == 'term' && arg(2)>0) {
    $term = taxonomy_get_term_by_name(arg(2));
    $language_terms = i18n_taxonomy_term_get_translation(array('tid' => arg(2)), $language->language);
  }

  if (count($languages[1])>1) {
    $lang_switcher = array();
    foreach ($languages[1] as $lang) {
      if ($lang->language != $language->language) {
        $modifier = $lang->native;
        //we are translating a node. Check if not neutral or missing translations.
        if ($language_paths && !empty($language_paths[$lang->language])) {
          $path = $language_paths[$lang->language];
        }
        //we are translating a term.
        if ($term) {
          $path = 'taxonomy/term/' . $language_terms[$lang->language]->tid;
        }
        $attributes = array('class' => 'link', 'lang' => $lang->language);
        $lang_switcher[] = l($modifier, $path, array('attributes' => $attributes, 'language' => $lang));
      }
    }
    return implode('<br />', $lang_switcher);
  }
}

/**
 * Implements hook_preprocess_node().
 */
function wetkit_language_preprocess_node(&$vars) {

}

/**
 * Revert specified features.
 *
 * @TODO Check that it really is Forced features revert.  Currently an exact
 * copy of the function initially placed in feature_projects.install.
 *
 * Code mostly taken from drush.
 */
function wetkit_language_features_revert($modules) {
  module_load_include('inc', 'features', 'features.export');
  features_include();
  foreach (
  $modules as $module) {
    if (($feature = feature_load($module, TRUE)) && module_exists($module)) {
      $components = array();
      // Forcefully revert all components of a feature.
      foreach (array_keys($feature->info['features']) as $component) {
        if (features_hook($component, 'features_revert')) {
          $components[] = $component;
        }
      }
    }
    foreach ($components as $component) {
      features_revert(array($module => array($component)));
    }
  }
}