<?php
/**
 * @file
 * Code for the wetkit_search module.
 */

include_once 'wetkit_search.features.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function wetkit_search_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_form_alter().
 */
function wetkit_search_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'search_form' || $form_id == 'search_theme_form') {
    $form['#submit'] = array('wetkit_search_all_form_submit');
    if (!empty($form['basic']['keys'])) {
      $form['basic']['keys']['#size'] = '';
    }
  }
}

/**
 * Custom form submit handler to change redirect state of the form.
 */
function wetkit_search_all_form_submit($form, &$form_state) {
  $keys = trim($form_state['values']['keys']);
  $form_state['redirect'] = array('search/site/' . $keys);
}

/**
 * Implements hook_modules_enabled().
 */
function wetkit_search_modules_enabled($modules) {

  // If we are running on a WetKit Compatible Server enable Solr support.
  if (in_array('wetkit_search', $modules) && variable_get('wetkit_tier') && module_enable(array('wetkit_solr'))) {

    // Supress the message from enabling Panopoly Apachesolr since we are
    // configuring it automatically.
    drupal_get_messages('status');

    // Load the Solr PHP Client Library.
    _search_api_solr_autoload('Apache_Solr_Service');
    _search_api_solr_autoload('Apache_Solr_HttpTransport_Abstract');

    // Push a WetKit Compatible Search API Schema.
    $schema_uri = drupal_get_path('module', 'search_api_solr') . '/schema.xml';
    wetkit_apachesolr_update_schema($schema_uri);

    // Enable Panopoly's Solr Server and Solr Index.
    require_once drupal_get_path('module', 'search_api') . '/search_api.admin.inc';
    $solr_server = search_api_server_load('solr_server');
    $solr_server->update(array('enabled' => 1));
    $solr_index = search_api_index_load('node_index');
    $solr_index->update(array('enabled' => 1));

    // Clear Solr Search Index and Rebuild.
    $solr_index->clear();
    $solr_index->reindex();
  }
}
