<?php
/**
 * @file
 * Code for the WetKit Demo feature.
 */

include_once 'wetkit_demo.features.inc';

/**
 * Implements hook_menu_alter().
 */
function wetkit_demo_menu_alter(&$items) {
  $items['node']['page callback'] = 'drupal_goto';
  $items['node']['page arguments'] = array('demo');
}

/**
 * Theme callback for the block configuration pages.
 *
 * @param $theme
 *   The theme whose blocks are being configured. If not set, the default theme
 *   is assumed.
 * @return
 *   The theme that should be used for the block configuration page, or NULL
 *   to indicate that the default theme should be used.
 */

/**
 * Implements hook_ctools_plugin_directory().
 *
 * @param type $module
 *   The module the plugin resides in for CTools
 * @param type $plugin
 *   The plugins name to reference for CTools
 * @return type
 *   The plugins autodetected by CTools
 */
function wetkit_demo_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_install().
 */
function wetkit_demo_install() {

}

/**
 * Implements hook_uninstall().
 */
function wetkit_demo_uninstall() {
  //menu_link_delete(null, '<front>');
}

/**
 * Implements hook_init().
 */
function wetkit_demo_init() {
  //Set Flag
  if ((variable_get('wetkit_demo_load', 1) == 1)) {
    $result_en = db_query("SELECT * FROM {defaultcontent}");
    foreach ($result_en as $record_en) {
      $result_fr = db_query('SELECT 1 FROM {defaultcontent} WHERE name = :name', array(':name' => $record_en->name . '-fr'))->fetchField();
      if ($result_fr) {
          $record_fr = db_query('SELECT * FROM {defaultcontent} WHERE name = :name', array(':name' => $record_en->name . '-fr'))->fetchObject();
          db_query('UPDATE {node} SET tnid = :tnid WHERE nid = :nid',
            array( ':tnid' => $record_en->nid, ':nid' => $record_en->nid));
          db_query('UPDATE {node} SET tnid = :tnid WHERE nid = :nid',
            array( ':tnid' => $record_en->nid, ':nid' => $record_fr->nid));
      }
    }
    variable_set('wetkit_demo_load', 0);
  }
}