<?php
/**
 * @file
 * Code for the WetKit Deployment Deployment feature.
 */

include_once 'wetkit_deployment.features.inc';
include_once 'wetkit_deployment.deploy_actions.inc';
include_once 'wetkit_deployment.deploy_queue.inc';
include_once 'theme/wetkit_deployment.theme.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function wetkit_deployment_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implements hook_menu().
 */
function wetkit_deployment_menu() {
  // Deployment menu link.
  $items['admin/dashboard/deployment/deploy'] = array(
    'type' => MENU_LOCAL_TASK,
    'title' => 'Menu Example',
    'description' => 'Simplest possible menu type, and the parent menu entry for others',
    'page callback' => '_wetkit_deployment_basic_instructions',
    'page arguments' => array('context' => 'wetkit_deployment'),
    'access callback' => TRUE,
    'menu_name' => 'navigation',
    'expanded' => TRUE,
  );
  return $items;
}

/**
 * Page callback for the simplest introduction menu entry.
 *
 * @param $content
 *   Some content passed in.
 */
function _wetkit_deployment_basic_instructions($context = NULL) {
  $deploy = deploy_plan_load($context);
  if ($deploy) {
    $deploy->deploy();
  }
  drupal_goto('admin/dashboard/deployment');
}

/**
 * Implements hook_theme().
 */
function wetkit_deployment_theme() {
  return array(
    'wetkit_deployment_items' => array(
      'variables' => array('items' => NULL),
    ),
    'wetkit_deploy_ui_overview' => array(
      'variables' => array('blocks' => array()),
    ),
    'wetkit_deploy_ui_overview_plan_content' => array(
      'variables' => array('info' => array()),
    ),
  );
}
  
/**
 * Allow modules to modify an entity before it gets deployed.
 *
 * @param $entity
 *   The entity being deployed.
 *
 * @param $entity_type
 *   The entity type; e.g. 'node' or 'user'.
 */
function wetkit_deployment_deploy_entity_alter(&$entity, $entity_type) {
  if ($entity_type = 'node') {
    //if (isset($entity->panelizer)) {
    //  unset($entity->panelizer);
    //}
  }
}

/**
 * Implements hook_deploy_aggregators().
 */
function wetkit_deployment_deploy_aggregators() {
  $path = drupal_get_path('module', 'wetkit_deployment') . '/plugins/deployment';
  return array(
    'WetKitDeployAggregatorManaged' => array(
      'name' => 'WetKit Managed aggregator',
      'description' => 'Provides methods for modules (or users) to manually manage entitites to be aggregated for deployment.',
      'handler' => array(
        'class' => 'WetKitDeployAggregatorManaged',
        'file' => 'WetKitDeployAggregatorManaged.inc',
        'path' => $path,
      ),
    ),
  );
}

/**
 * Implements hook_deploy_processors().
 */
function wetkit_deployment_deploy_processors() {
  $path = drupal_get_path('module', 'wetkit_deployment') . '/plugins/deployment';
  return array(
    'WetKitDeployProcessorQueue' => array(
      'name' => 'WetKit Queue API',
      'description' => 'All entities are processed with the Queue API. Works best when deployments are large.',
      'handler' => array(
        'class' => 'WetKitDeployProcessorQueue',
        'file' => 'WetKitDeployProcessorQueue.inc',
        'path' => $path,
      ),
    ),
  );
}

/**
 * Implements hook_cron_queue_info().
 */
function wetkit_deployment_cron_queue_info() {
  return array(
    'wetkit_deploy' => array(
      'worker callback' => 'wetkit_deployment_worker_deploy',
      'time' => 60,
    ),
    'wetkit_publish' => array(
      'worker callback' => 'wetkit_deployment_worker_publish',
      'time' => 60,
    ),
  );
}

/**
 * Processes a single queued item for deployment.
 */
function wetkit_deployment_worker_deploy($entity, &$context = NULL) {
  global $user;
  //if ($entity->__metadata['current_user'] == $user->uid) {
    $endpoint = deploy_endpoint_load($entity->__metadata['endpoint_name']);
    $plan = deploy_plan_load($entity->__metadata['plan_name']);

    if ($plan && $endpoint) {
      $entities = array(array('type' => $entity->__metadata['type'], 'id' => $entity->__metadata['id']));
      $iterator = deploy_iterator($entities);
      $endpoint->deploy($entity->__metadata['deployment_key'], $iterator, $entity->__metadata['lock_name']);
    }
  //}
}

/**
 * Processes a single queued item for publishing.
 */
function wetkit_deployment_worker_publish($entity, &$context = NULL) {
  global $user;
  //if (($entity->__metadata['current_user'] == $user->uid) && user_access('administer deployments')) {
    $endpoint = deploy_endpoint_load($entity->__metadata['endpoint_name']);
    $plan = deploy_plan_load($entity->__metadata['plan_name']);

    if ($plan && $endpoint) {
      $entities = array(array('type' => $entity->__metadata['type'], 'id' => $entity->__metadata['id']));
      $iterator = deploy_iterator($entities);
      $endpoint->publish($entity->__metadata['deployment_key'], $iterator, $entity->__metadata['lock_name']);

      $context['results'][$entity->__metadata['endpoint_name']] = $entity->__metadata['plan_name'];
    }
  //}
}

/**
 * Implements hook_form_alter().
 */
function wetkit_deployment_form_alter(&$form, &$form_state, $form_id) {
  // Peform logic on generic total control types.
  $deployment_types = array(
    'wetkit_deployment_deployment_edit_form',
    'wetkit_deployment_queue_edit_form',
  );
  if (in_array($form_id, $deployment_types)) {
    // Create General Settings Fieldset.
    $form['general_settings'] = array(
      '#type' => 'fieldset',
      '#title' => t('General Settings'),
      '#collapsible' => FALSE,
      '#collapsed' => FALSE,
    );
    $form['general_settings']['override_title'] = $form['override_title'];
    $form['general_settings']['override_title_markup'] = $form['override_title_markup'];
    $form['general_settings']['override_title_text'] = $form['override_title_text'];
    $form['general_settings']['types'] = $form['types'];

    // Unset some Form Variables.
    unset($form['override_title']);
    unset($form['override_title_markup']);
    unset($form['override_title_text']);
    unset($form['types']);
  }
}

/**
 * Implements hook_entity_dependencies().
 */
function wetkit_deployment_entity_dependencies($entity, $entity_type) {
  if ($entity_type == 'node') {
    $dependencies = array();
    $body = field_get_items('node', $entity, 'body');
    if ($body) {
      preg_match(MEDIA_TOKEN_REGEX, $body[0]['value'], $matches);
      if (isset($matches[0])) {
        $tag = $matches[0];
        $tag = str_replace(array('[[', ']]'), '', $tag);
        $tag_info = drupal_json_decode($tag);
        $dependencies[] = array('type' => 'file', 'id' => $tag_info['fid']);
      }
    }
    return $dependencies;
  }
}

/**
 * Implements hook_quicktabs_tabstyles().
 */
function wetkit_deployment_quicktabs_tabstyles() {
  $path = drupal_get_path('module', 'wetkit_deployment');
  return array(
    $path . '/plugins/quicktabs_styles/wetkit_tabs/wetkit_tabs.css' => t('WetKit Tabs'),
  );
}

/**
 * Implements hook_action_info().
 */
function wetkit_deployment_action_info() {
  $actions = array();
  $actions['wetkit_deployment_action_add_content_to_managed_plan'] = array(
    'type' => 'node',
    'label' => t('Add content to managed deployment plan'),
    'configurable' => FALSE,
  );
  $actions['wetkit_deployment_action_delete_content_from_managed_plan'] = array(
    'type' => 'node',
    'label' => t('Delete content from managed deployment plan'),
    'configurable' => FALSE,
  );
  $actions['wetkit_deployment_action_add_bean_to_managed_plan'] = array(
    'type' => 'bean',
    'label' => t('Add bean to managed deployment plan'),
    'configurable' => FALSE,
  );
  $actions['wetkit_deployment_action_delete_bean_from_managed_plan'] = array(
    'type' => 'bean',
    'label' => t('Delete bean from managed deployment plan'),
    'configurable' => FALSE,
  );
  $actions['wetkit_deployment_action_add_file_to_managed_plan'] = array(
    'type' => 'file',
    'label' => t('Add file to managed deployment plan'),
    'configurable' => FALSE,
  );
  $actions['wetkit_deployment_action_delete_file_from_managed_plan'] = array(
    'type' => 'file',
    'label' => t('Delete file from managed deployment plan'),
    'configurable' => FALSE,
  );
  $actions['wetkit_deployment_action_add_term_to_managed_plan'] = array(
    'type' => 'taxonomy_term',
    'label' => t('Add term to managed deployment plan'),
    'configurable' => FALSE,
  );
  $actions['wetkit_deployment_action_delete_term_from_managed_plan'] = array(
    'type' => 'taxonomy_term',
    'label' => t('Delete term from managed deployment plan'),
    'configurable' => FALSE,
  );
  $actions['wetkit_deployment_action_add_user_to_managed_plan'] = array(
    'type' => 'user',
    'label' => t('Add user to managed deployment plan'),
    'configurable' => FALSE,
  );
  $actions['wetkit_deployment_action_delete_user_from_managed_plan'] = array(
    'type' => 'user',
    'label' => t('Delete user from managed deployment plan'),
    'configurable' => FALSE,
  );
  return $actions;
}

/**
 * Options callback for the deploy_plan data type.
 */
function wetkit_deployment_deploy_manager_plan_get_options($args = array()) {
  $default_args = array(
    'aggregator_plugin' => 'WetKitDeployAggregatorManaged',
  );
  $args = array_merge($default_args, $args);

  $plans = deploy_plan_load_all($args);
  $options = array();
  foreach ($plans as $plan_name => $info) {
    $options[$plan_name] = $info->title;
  }
  return $options;
}
