<?php
/**
 * @file
 * Code for the Panopoly Search feature.
 */

include_once 'wetkit_search.features.inc';

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function wetkit_search_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
}

/**
 * Implementation of hook_form_alter()
 */
function wetkit_search_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'search_form' || $form_id == 'search_theme_form') {
    $form['#submit'] = array('wetkit_search_all_form_submit');
    if (!empty($form['basic']['keys'])) {
      $form['basic']['keys']['#size'] = '';
    }
  }
}

/**
 * Custom form submit handler to change redirect state of the form
 */
function wetkit_search_all_form_submit($form, &$form_state) {
  $keys = trim($form_state['values']['keys']);
  $form_state['redirect'] = array('search/site/' . $keys);
}

/**
 * Implementation of hook_preprocess_radio()
 */
function wetkit_search_preprocess_radio (&$variables) {
  $element = &$variables['element'];
  if ((isset($element['#name'])) && $element['#name'] == 'custom_search_paths') {
    $variables['theme_hook_suggestions'][] = 'radio__wetkitlayout';
  }
}

/**
 * Custom Template
 */
function theme_radio__wetkitlayout($variables) {
  $element = $variables['element'];
  $element['#attributes']['type'] = 'radio';
  element_set_attributes($element, array('id', 'name','#return_value' => 'value'));

  if (isset($element['#return_value']) && $element['#value'] !== FALSE && $element['#value'] == $element['#return_value']) {
    $element['#attributes']['checked'] = 'checked';
  }
  _form_set_class($element, array('form-radio'));

  return '<input' . drupal_attributes($element['#attributes']) . ' />';
}

/**
 * Implementation of hook_theme()
 */
function wetkit_search_theme($existing, $type, $theme, $path) {
   return array(
     'radio__wetkitlayout' => array(
       'render element' => 'element',
     ),
  );
}