<?php
/**
 * @file
 * Code for the wetkit_search feature.
 */

include_once('wetkit_search.features.inc');

/**
 * Implementation of hook_preprocess_radio()
 */
function wetkit_search_preprocess_radio (&$variables) {
  $element = &$variables['element'];
  if ((isset($element['#name'])) && $element['#name'] == 'custom_search_paths') {
    $variables['theme_hook_suggestions'][] = 'radio__wetkitlayout';
  }
}

/**
 * Custom Template
 */
function theme_radio__wetkitlayout($variables) {
  $element = $variables['element'];
  $element['#attributes']['type'] = 'radio';
  element_set_attributes($element, array('id', 'name','#return_value' => 'value'));

  if (isset($element['#return_value']) && $element['#value'] !== FALSE && $element['#value'] == $element['#return_value']) {
    $element['#attributes']['checked'] = 'checked';
  }
  _form_set_class($element, array('form-radio'));

  return '<input' . drupal_attributes($element['#attributes']) . ' />';
}

/**
 * Implementation of hook_theme()
 */
function wetkit_search_theme($existing, $type, $theme, $path) {
   return array(
     'radio__wetkitlayout' => array(
       'render element' => 'element',
     ),
  );
}
