name = WetKit Search
description = Integrates WetKit Search into Drupal.
machine_name = wetkit_search
version = 1.0-beta3
downloadable = wetkit_search 7.x-1.0-beta3
author = Pantheon Systems
author_url = http://www.getpantheon.com
screenshots[] = wetkit_search_screenshot.png
logo = wetkit_search_logo.png