<?php
/**
 * @file
 * Code for the wetkit_deployment_service feature.
 */

include_once 'wetkit_deployment_service.features.inc';

/**
 * Implements hook_entity_uuid_load().
 */
function wetkit_deployment_service_entity_uuid_load(&$entities, $entity_type) {
  //if ($entity_type == 'bean') {
  //  entity_property_id_to_uuid($entities, 'bean', 'bid');
  //}
  watchdog('Devel: WETKIT DEPLOYMENT load', 'Output of %live.', array('%live' => print_r($entity_type, TRUE)), WATCHDOG_NOTICE);
}

/**
 * Implements hook_entity_uuid_presave().
 */
function wetkit_deployment_service_entity_uuid_presave(&$entity, $entity_type) {
  if ($entity_type == 'node') {
    //entity_property_uuid_to_id($entity, 'node', 'vuuid');
    watchdog('Devel: WETKIT DEPLOYMENT presave', 'Output of %live.', array('%live' => print_r($entity, TRUE)), WATCHDOG_NOTICE);
    foreach ($entity->panelizer as $key => $value) {
      $entity->panelizer[$key] = (object) $value;
    }
    foreach ($entity->workbench_moderation as $key => $value) {
      $entity->workbench_moderation[$key] = (object) $value;
    }
  }
  if ($entity_type == 'user') {
    foreach ($entity->panelizer as $key => $value) {
      $entity->panelizer[$key] = (object) $value;
    }
    watchdog('Devel: WETKIT DEPLOYMENT user presave', 'Output of %live.', array('%live' => print_r($entity, TRUE)), WATCHDOG_NOTICE);
  }
}

/**
 * Implements hook_entity_uuid_presave().
 */
function wetkit_deployment_service_entity_uuid_save(&$entity, $entity_type) {
  //if ($entity_type == 'bean') {
  //  entity_property_uuid_to_id($entity, 'bean', 'bid');
  //}
  watchdog('Devel: WETIT DEPLOYMENT save', 'Output of %live.', array('%live' => print_r($entity_type, TRUE)), WATCHDOG_NOTICE);
}

/**
 * Implements hook_services_resources_alter().
 */
function wetkit_deployment_service_services_resources_alter(&$resources, &$endpoint) {
  $resources['file']['operations']['delete']['access callback'] = '_wetkit_deployment_service_access_file';
  $resources['file']['operations']['retrieve']['access callback'] = '_wetkit_deployment_service_access_file';
  $resources['file']['operations']['update']['access callback'] = '_wetkit_deployment_service_access_file';
}

/**
 * Custom Access File Callback.
 */
function _wetkit_deployment_service_access_file() {
  return TRUE;
}
