<?php

/**
 * Implements hook_ctools_plugin_api().
 */
function wetkit_box_ctools_plugin_api($module, $api) {
  list($module, $api) = func_get_args();
  if ($module == "spaces" && $api == "plugins") {
    return array("version" => "3");
  }
  list($module, $api) = func_get_args();
  if ($module == "boxes" && $api == "plugins") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_boxes_plugins().
 */
function wetkit_box_boxes_plugins() {
  $info = array();
  $path = drupal_get_path('module', 'wetkit_box') . '/plugins';
  $info['wetkit_box'] = array(
    'title' => 'Multilingual box',
    'handler' => array(
      'parent' => 'box',
      'class' => 'wetkit_box',
      'file' => 'wetkit_box.inc',
      'path' => $path,
    ),
  );
  return $info;
}

/**
 * Implementation hook_theme_registry_alter()
 */
function wetkit_box_theme_registry_alter(&$theme_registry) {
  $mod_path = drupal_get_path('module', 'wetkit_box') . '/templates';
  $theme_registry_copy = $theme_registry;
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'pow', $mod_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
}