<?php
/**
 * @file
 * Code for the WetKit Users feature.
 */

include_once 'wetkit_users.features.inc';

/**
 * Implements hook_init().
 */
function wetkit_users_init() {
  if (variable_get('wetkit_users_set', 1) == 1) {
    //Assign user 1 the "administrator" role.
    //$admin_role = user_role_load_by_name('administrator');
    db_insert('users_roles')
      ->fields(array('uid' => 1, 'rid' => 3))
      ->execute();
    variable_set('wetkit_users_set', 0);
  }
}