<?php
/**
 * @file
 * Code for the wetkit_web_usability feature.
 */

include_once('wetkit_web_usability.features.inc');

/**
 * Implements hook_install().
 */
function wetkit_web_usability_install() {
  /* Header Navigation */
  _add_custom_menu('http://www.canada.gc.ca/home.html', 'Canada.gc.ca', NULL, 'menu-wet-header', 0, 'en');
  _add_custom_menu('http://www.servicecanada.gc.ca/eng/home.shtml', 'Services', NULL, 'menu-wet-header', 1, 'en');
  _add_custom_menu('http://www.canada.gc.ca/depts/major/depind-eng.html', 'Departments', NULL, 'menu-wet-header', 2, 'en');
  _add_custom_menu('http://www.canada.gc.ca/accueil.html', 'Canada.gc.ca', NULL, 'menu-wet-header', 0, 'fr');
  _add_custom_menu('http://www.servicecanada.gc.ca/fra/accueil.shtml', 'Services', NULL, 'menu-wet-header', 1, 'fr');
  _add_custom_menu('http://www.canada.gc.ca/depts/major/depind-fra.html', 'Ministères', NULL, 'menu-wet-header', 2, 'fr');
  
  /* Mega Menu Navigation */
  $menu_depth1 = _add_custom_menu('<front>', 'Home', NULL, 'main-menu', 0, 'en');
  $menu_depth2 = _add_custom_menu('<front>', 'Sample Title', NULL, 'main-menu', 0, 'en', 0, $menu_depth1);
  _add_custom_menu('<front>', 'Sample Content', NULL, 'main-menu', 0, 'en', 0, $menu_depth2);
  $menu_depth2 = _add_custom_menu('<front>', 'Sample Title', NULL, 'main-menu', 0, 'en', 0, $menu_depth1);
  _add_custom_menu('<front>', 'Sample Content', NULL, 'main-menu', 0, 'en', 0, $menu_depth2);
  $menu_depth1 = _add_custom_menu('<front>', 'Help', NULL, 'main-menu', 1, 'en');
  $menu_depth2 = _add_custom_menu('<front>', 'Sample Title', NULL, 'main-menu', 0, 'en', 0, $menu_depth1);
  _add_custom_menu('<front>', 'Sample Content', NULL, 'main-menu', 0, 'en', 0, $menu_depth2);
  _add_custom_menu('<front>', 'Contact Us', NULL, 'main-menu', 2, 'en');
  _add_custom_menu('search', 'Search', NULL, 'main-menu', 3, 'en');
  _add_custom_menu('http://www.canada.gc.ca', 'canada.gc.ca', NULL, 'main-menu', 4, 'en');
  $menu_depth1 = _add_custom_menu('<front>', 'Accueil', NULL, 'main-menu', 0, 'fr');
  $menu_depth2 = _add_custom_menu('<front>', 'Exemple titre', NULL, 'main-menu', 0, 'fr', 0, $menu_depth1);
  _add_custom_menu('<front>', 'Exemple contenu', NULL, 'main-menu', 0, 'fr', 0, $menu_depth2);
  $menu_depth2 = _add_custom_menu('<front>', 'Exemple titre', NULL, 'main-menu', 0, 'fr', 0, $menu_depth1);
  _add_custom_menu('<front>', 'Exemple contenu', NULL, 'main-menu', 0, 'fr', 0, $menu_depth2);
  $menu_depth1 = _add_custom_menu('<front>', 'Aide', NULL, 'main-menu', 1, 'fr');
  $menu_depth2 = _add_custom_menu('<front>', 'Exemple contenu', NULL, 'main-menu', 0, 'fr', 0, $menu_depth1);
  _add_custom_menu('<front>', 'Exemple contenu', NULL, 'main-menu', 0, 'fr', 0, $menu_depth2);
  _add_custom_menu('<front>', 'Nous Contacter', NULL, 'main-menu', 2, 'fr');
  _add_custom_menu('search', 'Recherche', NULL, 'main-menu', 3, 'fr');
  _add_custom_menu('http://www.canada.gc.ca', 'canada.gc.ca', NULL, 'main-menu', 4, 'fr');
  
  /* Terms and Transparency Navigation */
  _add_custom_menu('<front>', 'Terms and Conditions', NULL, 'menu-wet-terms', 0, 'en');
  _add_custom_menu('<front>', 'Transparency', NULL, 'menu-wet-terms', 1, 'en');
  _add_custom_menu('<front>', 'Avis', NULL, 'menu-wet-terms', 0, 'fr');
  _add_custom_menu('<front>', 'Transparence', NULL, 'menu-wet-terms', 1, 'fr');
  
  /* Mid Footer Navigation */
  $menu_depth1 = _add_custom_menu('<front>', 'About Us', NULL, 'menu-wet-mid-footer', 0, 'en');
  _add_custom_menu('<front>', 'Our Mandate', NULL, 'menu-wet-mid-footer', 0, 'en', 0, $menu_depth1);
  _add_custom_menu('<front>', 'Our Minister', NULL, 'menu-wet-mid-footer', 1, 'en', 0, $menu_depth1);
  $menu_depth1 = _add_custom_menu('<front>', 'News', NULL, 'menu-wet-mid-footer', 1, 'en');
  _add_custom_menu('<front>', 'News Releases', NULL, 'menu-wet-mid-footer', 0, 'en', 0, $menu_depth1);
  _add_custom_menu('<front>', 'Media Advisories', NULL, 'menu-wet-mid-footer', 1, 'en', 0, $menu_depth1);
  _add_custom_menu('<front>', 'Multimedia', NULL, 'menu-wet-mid-footer', 2, 'en', 0, $menu_depth1);
  $menu_depth1 = _add_custom_menu('<front>', 'Contact Us', NULL, 'menu-wet-mid-footer', 2, 'en');
  _add_custom_menu('<front>', 'Phone Numbers', NULL, 'menu-wet-mid-footer', 0, 'en', 0, $menu_depth1);
  _add_custom_menu('<front>', 'Find an Employee', NULL, 'menu-wet-mid-footer', 1, 'en', 0, $menu_depth1);
  $menu_depth1 = _add_custom_menu('<front>', 'Stay Connected', NULL, 'menu-wet-mid-footer', 3, 'en');
  _add_custom_menu('<front>', 'Youtube', NULL, 'menu-wet-mid-footer', 0, 'en', 0, $menu_depth1);
  _add_custom_menu('<front>', 'Twitter', NULL, 'menu-wet-mid-footer', 1, 'en', 0, $menu_depth1);
  _add_custom_menu('<front>', 'Feeds', NULL, 'menu-wet-mid-footer', 2, 'en', 0, $menu_depth1);
  $menu_depth1 = _add_custom_menu('<front>', 'À propos de nous', NULL, 'menu-wet-mid-footer', 0, 'fr');
  _add_custom_menu('<front>', 'Notre mandat', NULL, 'menu-wet-mid-footer', 0, 'fr', 0, $menu_depth1);
  _add_custom_menu('<front>', 'Le ministre', NULL, 'menu-wet-mid-footer', 1, 'fr', 0, $menu_depth1);
  $menu_depth1 = _add_custom_menu('<front>', 'Média', NULL, 'menu-wet-mid-footer', 1, 'fr');
  _add_custom_menu('<front>', 'Communiqués', NULL, 'menu-wet-mid-footer', 0, 'fr', 0, $menu_depth1);
  _add_custom_menu('<front>', 'Avis aux médias', NULL, 'menu-wet-mid-footer', 1, 'fr', 0, $menu_depth1);
  _add_custom_menu('<front>', 'Multimedia', NULL, 'menu-wet-mid-footer', 2, 'fr', 0, $menu_depth1);
  $menu_depth1 = _add_custom_menu('<front>', 'Contactez-nous', NULL, 'menu-wet-mid-footer', 2, 'fr');
  _add_custom_menu('<front>', 'Numéros de téléphone', NULL, 'menu-wet-mid-footer', 0, 'fr', 0, $menu_depth1);
  _add_custom_menu('<front>', 'Trouvez un(e) employé(e)', NULL, 'menu-wet-mid-footer', 1, 'fr', 0, $menu_depth1);
  $menu_depth1 = _add_custom_menu('<front>', 'Restez branchés', NULL, 'menu-wet-mid-footer', 3, 'fr');
  _add_custom_menu('<front>', 'Youtube', NULL, 'menu-wet-mid-footer', 0, 'fr', 0, $menu_depth1);
  _add_custom_menu('<front>', 'Twitter', NULL, 'menu-wet-mid-footer', 1, 'fr', 0, $menu_depth1);
  _add_custom_menu('<front>', 'Fils de nouvelles', NULL, 'menu-wet-mid-footer', 2, 'fr', 0, $menu_depth1);

  /* Footer Navigation */
  _add_custom_menu('http://healthycanadians.gc.ca/index-eng.php', 'Health', 'healthycanadians.gc.ca', 'menu-wet-footer', 0, 'en');
  _add_custom_menu('http://www.voyage.gc.ca/index-eng.asp', 'Travel', 'travel.gc.ca', 'menu-wet-footer', 1, 'en');
  _add_custom_menu('http://www.servicecanada.gc.ca/eng/home.shtml', 'Service Canada', 'servicecanada.gc.ca', 'menu-wet-footer', 2, 'en');
  _add_custom_menu('http://www.jobbank.gc.ca/intro-eng.aspx', 'Jobs', 'jobbank.gc.ca', 'menu-wet-footer', 3, 'en');
  _add_custom_menu('http://actionplan.gc.ca/eng/index.asp', 'Economy', 'actionplan.gc.ca', 'menu-wet-footer', 4, 'en');
  _add_custom_menu('http://www.canada.gc.ca/home.html', 'Canada.gc.ca', NULL, 'menu-wet-footer', 5, 'en');
  _add_custom_menu('http://canadiensensante.gc.ca/index-fra.php', 'Santé', 'canadiensensante.gc.ca', 'menu-wet-footer', 0, 'fr');
  _add_custom_menu('http://voyage.gc.ca/index-fra.asp', 'Voyage', 'voyage.gc.ca', 'menu-wet-footer', 1, 'fr');
  _add_custom_menu('http://www.servicecanada.gc.ca/fra/accueil.shtml', 'Service Canada', 'servicecanada.gc.ca', 'menu-wet-footer', 2, 'fr');
  _add_custom_menu('http://www.guichetemplois.gc.ca/Intro-fra.aspx', 'Emplois', 'guichetemplois.gc.ca', 'menu-wet-footer', 3, 'fr');
  _add_custom_menu('http://www.plandaction.gc.ca/', 'Économie', 'plandaction.gc.ca', 'menu-wet-footer', 4, 'fr');
  _add_custom_menu('http://www.canada.gc.ca/accueil.html', 'Canada.gc.ca', NULL, 'menu-wet-footer', 5, 'fr');

  //Clears all menu caches
  menu_cache_clear_all();
}

/**
 * Implements hook_uninstall().
 */
function wetkit_web_usability_uninstall() {
  variable_del('views_temp');
}

/**
 * Implements hook_page_alter().
 */
function wetkit_web_usability_page_alter(&$page) {
  //Hides the toolbar for administrator users if enabled
  if (module_exists('toolbar')) {
    global $user;
    if (in_array("administrator", $user->roles)) {
      unset($page['page_top']['toolbar']);
    }
  }
}

/**
 * Implements hook_enable().
 */
function wetkit_web_usability_init() {
  //Set Flag
  if ((variable_get('wetkit_web_usability_load', 1) == 1)) {
    drupal_flush_all_caches();
    variable_set('wetkit_web_usability_load', 0);
  }
  //Set Documentation Text
  if ((variable_get('wetkit_web_usability_doc', 1) == 1) && user_is_logged_in()) {
    drupal_set_message(t('Please proceed to the <a href="@settings">WetKit Web Usability Page</a> to configure additional settings.', array('@settings' => url('admin/config/wetkit_web_usability/settings'))), 'status');
    drupal_set_message(t('Please read the online <a href="@documentation">Documentation</a>', array('@documentation' => url('http://wetkit.atlassian.com/wiki'))), 'warning');
    variable_set('wetkit_web_usability_doc', 0);
  }
  //Add WET pe-ap.js on hook_init
  $current_path = current_path();
  if (function_exists('libraries_get_path') && (!path_is_admin($current_path)) && variable_get('wetkit_web_usability_v1', 1)) {
    $library_path = libraries_get_path('wet-boew');
    drupal_add_js($library_path . '/src/theme-gcwu-fegc/js/theme.js', array('scope' => 'footer', 'weight' => 5));
    drupal_add_js($library_path . '/src/js/workers/menubar.js', array('scope' => 'footer', 'weight' => 5));
    drupal_add_js($library_path . '/src/js/workers/toolbar.js', array('scope' => 'footer', 'weight' => 5));
    drupal_add_js($library_path . '/src/js/settings.js', array('scope' => 'footer', 'weight' => 5));
    drupal_add_js($library_path . '/src/js/pe-ap.js', array('scope' => 'footer', 'weight' => 5));
  }
}

/**
* Implementation of hook_menu().
*/
function wetkit_web_usability_menu() {
  $items['admin/config/wetkit_web_usability'] = array(
    'title' => 'WetKit Web Usability',
    'description' => 'Manage specific features related to the Web Experience Toolkit.',
    'position' => 'left',
    'weight' => -50,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/wetkit_web_usability/settings'] = array(
    'title' => 'WetKit Web Usability Settings',
    'description' => 'Change how certain settings behave from the Web Experience Toolkit.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wetkit_web_usability_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'wetkit_web_usability.admin.inc',
  );
  return $items;
}

/* HELPER FUNCTIONS */

/**
 * Implements _add_custom_menu().
 */
function _add_custom_menu($link, $title, $desc, $menu, $weight, $language, $mlid = 0, $plid = 0) {
  $options = array();
  if ($desc != NULL) {
    $options += array(
      'attributes' => array(
        'title' => $desc,
      ),
    );
  }
  $item = array(
    'link_path' => $link,
    'link_title' => $title,
    'menu_name' => $menu,
    'weight' => $weight,
    'language' => $language,
    'customized' => 1,
    'options' => $options,
    'mlid' => $mlid,
    'plid' => $plid,
  );
  return menu_link_save($item);
}
