name = WetKit Pages
description = Integrates WetKit Pages search into Drupal.
machine_name = wetkit_pages
version = 1.0-beta3
downloadable = wetkit_pages 7.x-1.0-beta3
author = Pantheon Systems
author_url = http://www.getpantheon.com
screenshots[] = wetkit_search_screen_1.png
logo = wetkit-icon.png