<?php
/**
 * @file
 * Code for the wetkit_slider feature.
 */

include_once('wetkit_slider.features.inc');

/**
 * Implements hook_install().
 */
function wetkit_slider_install() {

}

/**
 * Implements hook_uninstall().
 */
function wetkit_slider_uninstall() {
  variable_del('views_slider');
}

/**
 * Implements hook_load().
 */
function wetkit_slider_init() {
  //Set Flag
  if (variable_get('views_slider', 1) == 1) {
    //Flush Drupal Caches
    drupal_flush_all_caches();
    //Create managed File object and associate with file field.
    $file1 = _slider_add_file('default_sliderpic1.png', drupal_get_path('theme', variable_get('theme_default')) . '/images/slider01.png');
    $file2 = _slider_add_file('default_sliderpic2.png', drupal_get_path('theme', variable_get('theme_default')) . '/images/slider02.png');

    //Slider Content
    $field_text_1_en = '<div class="tabs-content-pad">
      <p>Take Note: <a href="http://news.gc.ca">Recent National News</a><br />
        Learn more about the <a href="http://canada.gc.ca">Government of Canada</a></p>
    </div>';
    $field_text_1_fr = '<div class="tabs-content-pad">
      <p>Prenez note: <a href="http://news.gc.ca">Dernières Nouvelles nationales</a><br />
       En savoir plus sur le <a href="http://canada.gc.ca">Gouvernement du Canada</a></p>
    </div>';

    //Add Two Slideshows for both EN and FR
    _slider_add_node('Front Page Slider Official 1', 'en', 3, 'First Slide Title', $file1, $field_text_1_en);
    _slider_add_node('Première page diaporama officiel 1', 'fr', 3, 'Titre première diaporama', $file1, $field_text_1_fr);
    _slider_add_node('Front Page Slider Official 2', 'en', 4, 'Second Slide Title', $file2, $field_text_1_en);
    _slider_add_node('Première page diaporama officiel 1', 'fr', 4, 'Titre dieuxème diaporama', $file2, $field_text_1_fr);
    variable_set('views_slider', 0);
  }
}

/**
 * Implements _slider_add_file().
 */
function _slider_add_file($filename, $filepath) {
  $file = new stdClass();
  $file->uid = 6;
  $file->uri = $filepath;
  $file->filename = $filename;
  $file->filemime = file_get_mimetype($file->uri);
  $file->status = 1;
  $dest = file_default_scheme() . '://' . $filename;
  $file = file_copy($file, $dest);
  $file->display = 1;
  $file->description = "";
  return $file;
}

/**
 * Implements _slider_add_node().
 */
function _slider_add_node($title, $langval, $tnid, $slider_title, $slider_file, $slider_desc) {
  $node = new stdClass();
  $node->type = 'main_slider';
  node_object_prepare($node);
  $node->title = $title;
  $node->language = $langval;
  $node->status = 1;
  $node->uid = 1;
  $node->tnid = $tnid;
  $node->field_slider_title['und'][0]['value'] = $slider_title;
  $node->field_slider_photo['und'][0] = (array)$slider_file;
  $node->field_slider_description['und'][0]['value'] = $slider_desc;
  $node->field_slider_description['und'][0]['format'] = 'full_html';
  $node->field_slider_description['und'][0]['safe_value'] = $slider_desc;
  node_save($node); 
}