<?php

include_once('wetkit_users.features.inc');

/**
 * Implementation of hook_apps_app_info()
 */
function wetkit_users_apps_app_info() {
  return array(
    'configure form' => 'wetkit_users_configure_form',
  );
}

/**
 * Configuration Form for WetKit Magic
 */
function wetkit_users_configure_form($form, &$form_state) {
  $form = array();

  $form['wetkit_users_login_destination'] = array(
    '#title' => t('Login Destination'),
    '#type' => 'textfield',
    '#required' => TRUE,
    '#default_value' => variable_get('wetkit_users_login_destination', '<front>'),
    '#description' => t('Where do you want to redirect users when the login using the standard login link? Use <front> for the Drupal frontpage.'),
  );

  $form['wetkit_users_remove_tabs'] = array(
     '#title' => t('Remove User Tabs'),
     '#type' => 'select',
     '#required' => TRUE,
     '#options' => array(
       0 => t('Do Not Remove'),
       1 => t('Remove'),
     ),
     '#default_value' => variable_get('wetkit_users_remove_tabs', TRUE),
     '#description' => t('Do you want to remove the login, reset password, and register tabs on the user page? These links will be transfered into the relevant field descriptions instead.'),
  );

  return system_settings_form($form);
}

/**
 * Implementation of hook_ctools_plugin_directory()
 */
function wetkit_users_ctools_plugin_directory($module, $plugin) {
  return 'plugins/' . $plugin;
} 

/**
 * Implementation of hook_menu_alter()
 */
function wetkit_users_menu_alter(&$items) {

  // Remove tabs from user login page
  if (variable_get('wetkit_users_remove_tabs', TRUE)) {
    $items['user/login']['type'] = MENU_CALLBACK;
    $items['user/register']['type'] = MENU_CALLBACK;
    $items['user/password']['type'] = MENU_CALLBACK;
  }
}

/**
 * Implementation of hook_form_alter()
 */
function wetkit_users_form_alter(&$form, $form_state, $form_id) {

  if (variable_get('wetkit_users_remove_tabs', TRUE)) {

    // Add a create account link below the username
    if ($form_id == 'user_login' && variable_get('user_register')) {
      $form['name']['#description'] .= '<br>' . t('If you don\'t have an username, !create.', array('!create' => l('create an account', 'user/register')));
    }

    // Add the request password link below the password
    if ($form_id == 'user_login') {
      $form['pass']['#description'] .= '<br>' . t('If you forgot your password, !request.', array('!request' => l('request a new password', 'user/password')));
    }
  }

  // Remove the title from the user picture field
  if ($form_id == 'user_profile_form') {
    if (!empty($form['field_user_picture']['und'][0]['#title'])) {
      unset($form['field_user_picture']['und'][0]['#title']);
    }
  }
}

/**
 * Implementation of hook_user_login()
 *
 * This will redirect the user to a specified page when they log in.
 */
function wetkit_users_user_login(&$edit, $account) {
  $edit['redirect'] = variable_get('wetkit_users_login_destination', '<front>');
}

/**
 * Implements hook_page_build().
 *
 * Hide the toolbar for user 1 and administrator role because uses the admin menu instead
 */
function wetkit_users_page_build(&$page) {
  $page['page_top']['toolbar']['#access'] = wetkit_users_toolbar_access();
}

/**
 * Implements wetkit_users_toolbar_access().
 */
function wetkit_users_toolbar_access() {
  global $user;
  if (($user->uid == 1) || (in_array('administrative user', array_values($user->roles)))) {
    return FALSE;
  }
  else {
    return user_access('access toolbar');
  }
}