<?php
/**
 * @file
 * Code for the wetkit_web_usability feature.
 */

include_once('wetkit_web_usability.features.inc');
include_once('wetkit_web_usability.menu_wetkit_load.inc');

/**
 * Implements hook_install().
 */
function wetkit_web_usability_install() {
  _menu_wetkit_load();
}

/**
 * Implements hook_uninstall().
 */
function wetkit_web_usability_uninstall() {
  variable_del('views_temp');
}

/**
* Implementation of hook_ctools_plugin_directory().
*/
function wetkit_web_usability_ctools_plugin_directory($module, $plugin) {
  if ($module == 'page_manager' || $module == 'panels') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_page_alter().
 */
function wetkit_web_usability_page_alter(&$page) {
  //Hides the toolbar for administrator users if enabled
  if (module_exists('toolbar')) {
    global $user;
    if (in_array("administrator", $user->roles)) {
      unset($page['page_top']['toolbar']);
    }
  }
}

/**
 * Implements hook_enable().
 */
function wetkit_web_usability_init() {
  //Set Flag
  if ((variable_get('wetkit_web_usability_load', 1) == 1)) {
    drupal_flush_all_caches();
    variable_set('wetkit_web_usability_load', 0);
  }
  //Set Documentation Text
  if ((variable_get('wetkit_web_usability_doc', 1) == 1) && user_is_logged_in()) {
    drupal_set_message(t('Please proceed to the <a href="@settings">WetKit Web Usability Page</a> to configure additional settings.', array('@settings' => url('admin/config/wetkit_web_usability/settings'))), 'status');
    drupal_set_message(t('Please read the online <a href="@documentation">Documentation</a>', array('@documentation' => url('https://github.com/wet-boew/wet-boew-drupal/wiki'))), 'warning');
    variable_set('wetkit_web_usability_doc', 0);
  }
  //Add WET pe-ap.js on hook_init
  $current_path = current_path();
  if (function_exists('libraries_get_path') && (!path_is_admin($current_path)) && variable_get('wetkit_web_usability_v1', 1)) {
    $library_path = libraries_get_path('wet-boew');
    //drupal_add_js($library_path . '/src/theme-gcwu-fegc/js/theme.js', array('scope' => 'footer', 'weight' => 5));
    //drupal_add_js($library_path . '/src/js/workers/menubar.js', array('scope' => 'footer', 'weight' => 5));
    //drupal_add_js($library_path . '/src/js/workers/toolbar.js', array('scope' => 'footer', 'weight' => 5));
    //drupal_add_js($library_path . '/src/js/settings.js', array('scope' => 'footer', 'weight' => 5));
    //drupal_add_js($library_path . '/src/js/pe-ap.js', array('scope' => 'footer', 'weight' => 5));
    drupal_add_js($library_path . '/build/theme-gcwu-fegc/js/theme-min.js', array('scope' => 'footer', 'weight' => 5));
    drupal_add_js($library_path . '/build/js/settings.js', array('scope' => 'footer', 'weight' => 5));
    drupal_add_js($library_path . '/build/js/pe-ap-min.js', array('scope' => 'footer', 'weight' => 5));
  }
}

/**
* Implementation of hook_menu().
*/
function wetkit_web_usability_menu() {
  $items['admin/config/wetkit_web_usability'] = array(
    'title' => 'WetKit Web Usability',
    'description' => 'Manage specific features related to the Web Experience Toolkit.',
    'position' => 'left',
    'weight' => -50,
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('administer site configuration'),
    'file' => 'system.admin.inc',
    'file path' => drupal_get_path('module', 'system'),
  );
  $items['admin/config/wetkit_web_usability/settings'] = array(
    'title' => 'WetKit Web Usability Settings',
    'description' => 'Change how certain settings behave from the Web Experience Toolkit.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('wetkit_web_usability_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'wetkit_web_usability.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_menu_block_blocks().
 */
function wetkit_web_usability_menu_block_blocks() {
  // The array key is the block delta used by menu block.
  return array(
    'wetkit_menu_blocks-1' => array(
      'menu_name'   => 'main-menu',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => 'Mega Menu',
      'level'       => 1,
      'follow'      => 0,
      'depth'       => 0,
      'expanded'    => 1,
      'sort'        => 1,
    ),
    'wetkit_menu_blocks-2' => array(
      'menu_name'   => 'menu-wet-mid-footer',
      'parent_mlid' => 0,
      'title_link'  => 0,
      'admin_title' => 'Footer Block',
      'level'       => 1,
      'follow'      => 0,
      'depth'       => 0,
      'expanded'    => 1,
      'sort'        => 0,
    ),
  );
}
