name = WetKit Admin
description = Integrates WetKit Admin into Drupal.
machine_name = wetkit_admin
version = 1.0-beta3
downloadable = wetkit_admin 7.x-1.0-beta3
author = Pantheon Systems
author_url = http://www.getpantheon.com
screenshots[] = wetkit_web_usability_1.png
logo = wetkit-icon.png
dependencies[views] = views 3.0-beta3
dependencies[ctools] = ctools 1.0-alpha4