name = WetKit Admin
description = Integrates WetKit Admin into Drupal.
machine_name = wetkit_admin
version = 1.0-beta3
downloadable = wetkit_admin 7.x-1.0-beta3
author = Pantheon Systems
author_url = http://www.getpantheon.com
screenshots[] = https://raw.github.com/wet-boew/wet-boew-drupal/master/modules/apps/wetkit_admin/app/wetkit_web_usability_1.png
logo = https://raw.github.com/wet-boew/wet-boew-drupal/master/modules/apps/wetkit_admin/app/wetkit-icon.png