<?php
// Plugin definition
$plugin = array(
  'title' => t('Rolph'),
  'icon' => 'rolph.png',
  'category' => t('Panopoly'),
  'theme' => 'rolph',
  'css' => 'rolph.css',
  'regions' => array(
    'header' => t('Header'),
    'quarter1' => t('Quarter 1 Column'),
    'quarter2' => t('Quarter 2 Column'),
    'quarter3' => t('Quarter 1 Column'),
    'quarter4' => t('Quarter 2 Column'),
    'footer' => t('Footer'),
  ),
);
