<?php

/**
 * Implements hook_ctools_plugin_api().
 */
function wetkit_box_ctools_plugin_api($module, $api) {
  list($module, $api) = func_get_args();
  if ($module == "spaces" && $api == "plugins") {
    return array("version" => "3");
  }
  list($module, $api) = func_get_args();
  if ($module == "boxes" && $api == "plugins") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_boxes_plugins().
 */
function wetkit_box_boxes_plugins() {
  $info = array();
  $path = drupal_get_path('module', 'wetkit_box') . '/plugins';
  $info['wetkit_box'] = array(
    'title' => 'Multilingual box',
    'handler' => array(
      'parent' => 'box',
      'class' => 'wetkit_box',
      'file' => 'wetkit_box.inc',
      'path' => $path,
    ),
  );
  return $info;
}