<?php
/**
 * @file
 * Metatag integration for the wetkit_metatag module.
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function wetkit_metatag_ctools_plugin_api($owner, $api) {
  if ($owner == 'metatag' && $api == 'metatag') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_theme().
 */
function wetkit_metatag_theme() {
  $info['wetkit_metatag'] = array(
    'render element' => 'element',
  );

  return $info;
}

/**
 * Theme callback for a Dublin Core meta tag.
 */
function theme_wetkit_metatag($variables) {
  $element = &$variables['element'];
  element_set_attributes($element, array(
    '#name' => 'name',
    '#schema' => 'title',
    '#value' => 'content')
  );
  unset($element['#value']);
  return theme('html_tag', $variables);
}

/**
 * Implements hook_form_alter().
 */
function wetkit_metatag_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'wetkit_page_node_form' || $form_id == 'wetkit_page_other_node_form') {
    unset($form['metatags']['advanced']);
    unset($form['metatags']['dublin-core']);
    unset($form['metatags']['tokens']);
  }
}
