<?php
/**
 * @file
 * Code for the WetKit Layout.
 */

include_once 'wetkit_migrate.features.inc';

/**
 * Implements hook_migrate_api().
 *
 * @return int
 *   Return the api version for migrate.
 */
function wetkit_migrate_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}

/**
 * Implements hook_migrate_menu().
 *
 * @return string
 *   Return the menu configuration.
 */
function wetkit_migrate_menu() {
  $items = array();

  $items['admin/config/development/wetkit_migration'] = array(
    'title' => 'WetKit Migration',
    'description' => 'Configure database settings for the WetKit content migration.',
    'page callback' => 'drupal_get_form',
    'file' => 'wetkit_migrate.pages.inc',
    'page arguments' => array('wetkit_migrate_form'),
    'access callback' => TRUE,
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_init().
 */
function wetkit_migrate_init() {

}
