name = WetKit Core
description = Integrates WetKit Core into Drupal.
machine_name = wetkit_core
version = 1.0-beta3
downloadable = wetkit_core 7.x-1.0-beta3
author = Pantheon Systems
author_url = http://www.getpantheon.com
screenshots[] = wetkit_core_screenshot.png
logo = wetkit_core_logo.png